### ISSUE TITLE
fix the message on registration section

### ISSUE THREAD

**Issue by RandyPaulEspejo** [prometheus-tech/kaagapAI#10]
**Describe the bug**
- kindly fix the message on the registration section.

**To Reproduce**
1. Go to '.kaagapai login..'
2. Click on '.. the registration..'
3. See error "kaagapAI is built for your needs. **Specific message here**."

**Expected behavior**

**Screenshots**
<img width="725" alt="Screen Shot 2019-04-26 at 8 44 09 PM" src="https://user-images.githubusercontent.com/37105236/56808688-a4a7f600-6864-11e9-84c9-6af6d6429809.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Mojave
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 73

**Comment by JessieMTabilisma** [comment]
We already updated the messages that will prompt to the user, also for empty messages.

**Comment by RandyPaulEspejo** [comment]
Thank you @JessieMTabilisma  @julianaubrey
