### ISSUE TITLE
Issues on Trash Bin

### ISSUE THREAD

**Issue by RandyPaulEspejo** [prometheus-tech/kaagapAI#20]
**Describe the bug**
- after restoring archiving file there is no back button.

**To Reproduce**
1. Go to '.trash bin..'
2. Click on '.restore a client...'
3. See error - there is no back button

**Expected behavior**
- user must be able to see a back button after restoring client and session

**Screenshots**
- <img width="1432" alt="Screen Shot 2019-04-27 at 1 26 01 AM" src="https://user-images.githubusercontent.com/37105236/56825522-f152f780-688b-11e9-902a-7dfc06580ee0.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Mojave
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 73

**Comment by JessieMTabilisma** [comment]
I already add and design a back button.

**Comment by RandyPaulEspejo** [comment]
Thank you @JessieMTabilisma
