### ISSUE TITLE
remove "My Account"

### ISSUE THREAD

**Issue by RandyPaulEspejo** [prometheus-tech/kaagapAI#28]
**Describe the bug**
- My Account is hanging and it will not be use anymore.

**To Reproduce**
1. Login your account
2. Click the icon on the upper right corner of page where it contains profile, "myaccount" and logout

**Expected behavior**
- remove the my account because it will not be use.

**Screenshots**
- 
<img width="1436" alt="Screen Shot 2019-04-27 at 10 51 20 AM" src="https://user-images.githubusercontent.com/37105236/56843943-76fd9400-68da-11e9-9532-0602886c17b8.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Mojave
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 73

**Comment by JessieMTabilisma** [comment]
Hi, @RandyPaulEspejo  I already removed this module.

**Comment by RandyPaulEspejo** [comment]
Thank you @JessieMTabilisma
