### ISSUE TITLE
issue on the adding client.... please check it out

### ISSUE THREAD

**Issue by RandyPaulEspejo** [prometheus-tech/kaagapAI#5]
**Describe the bug**
-both field on the firstname and lastname is accepting pure spaces. on adding client
- and also it accepting a special character like this one "-".

**To Reproduce**
1. Go to 'new client button'
2. Click on 'first name field and fill it up with three space as well as the last name' and also try in another session 'fill in with one letter and put "-".'
4. See error it accepting just spaces, so there is no validation for spaces and also i think you misplace a special character like this one "-"

**Expected behavior**
- it should not accept all space
-it should not accept character like this one "-"

**Screenshots**
*screenshot for the firstname field
--space error
<img width="610" alt="Screen Shot 2019-03-27 at 6 53 37 AM" src="https://user-images.githubusercontent.com/37105236/55039180-2b976200-505e-11e9-9689-0218cbfdd528.png">
--special character error
![Screen Shot 2019-03-27 at 6 57 37 AM](https://user-images.githubusercontent.com/37105236/55039530-69e15100-505f-11e9-8833-fe277d387004.png)

*screenshot for the lastname field
--space error
<img width="609" alt="Screen Shot 2019-03-27 at 6 54 21 AM" src="https://user-images.githubusercontent.com/37105236/55039288-89c44500-505e-11e9-9af6-2ea6aa67b76e.png">
--special character error
![Screen Shot 2019-03-27 at 6 58 02 AM](https://user-images.githubusercontent.com/37105236/55039546-7b2a5d80-505f-11e9-82f4-ef40fe4b9cb3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Mojave
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] ver 72

**Comment by julianaubrey** [comment]
Hi @RandyPaulEspejo! I have provided a fix on the **spaces-only issue**. However, I did not provide a fix on the special symbols anymore because @Jodyadriene mentioned that we won't be handling those scenarios anymore. Let me know when you have other concerns related to this raised issue. Thanks!

**Comment by julianaubrey** [comment]
@RandyPaulEspejo I have also implemented the trimming of consecutive spaces between strings. Check it out!
