### ISSUE TITLE
issues  on editing client information .... please check it out

### ISSUE THREAD

**Issue by RandyPaulEspejo** [prometheus-tech/kaagapAI#6]
**Describe the bug**
-it accepting spaces only and a special character like this "-" on the both field in first name and last name.

**To Reproduce**
1. Go to 'client name'
2. Click on 'edit and set text like spaces only and also set text like o- on both field in first name and last name'
4. See error it should be verify the validation on the spaces and special character

**Expected behavior**
-it should be prompt a error message

**Screenshots**
-screenshot for firstname
---spaces
![Screen Shot 2019-03-27 at 7 39 17 AM](https://user-images.githubusercontent.com/37105236/55040610-18879080-5064-11e9-9ebf-63a199704f5e.png)
--special character
![Screen Shot 2019-03-27 at 7 39 50 AM](https://user-images.githubusercontent.com/37105236/55040620-21786200-5064-11e9-95e9-49385954d530.png)

-screenshot for the last name
---spaces
![Screen Shot 2019-03-27 at 7 39 37 AM](https://user-images.githubusercontent.com/37105236/55040634-3228d800-5064-11e9-8ba3-19863bec564e.png)
---special character
![Screen Shot 2019-03-27 at 7 40 02 AM](https://user-images.githubusercontent.com/37105236/55040641-3a811300-5064-11e9-94a8-a090e4553f06.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac os
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 76

**Smartphone (please complete the following information):**

**Additional context**

**Comment by julianaubrey** [comment]
Hi @RandyPaulEspejo! I have provided a fix on the **spaces-only issue**. However, I did not provide a fix on the special symbols anymore because @Jodyadriene mentioned that we won't be handling those scenarios anymore. Let me know when you have other concerns related to this raised issue. Thanks!

**Comment by julianaubrey** [comment]
@RandyPaulEspejo I have also implemented the trimming of consecutive spaces between strings. Check it out!

**Comment by RandyPaulEspejo** [comment]
@julianaubrey done checking on the trimming of spaces between string
