### ISSUE TITLE
Cannot Continue Account Registration after Closing Browser on Step 2

### ISSUE THREAD

**Issue by julianaubrey** [prometheus-tech/kaagapAI#7]
**Describe the bug**
As a user, I don't know how to proceed with the account registration if I accidentally close the browser after submitting my account information and before submitting the verification code.

**To Reproduce**
Steps to reproduce the behavior (assuming that you are running the frontend on dev configuration):
1. Go to http://kaagapai-dev:3000/signup
2. Completely fill out the form on the 'Account Registration' step
3. Click 'Next'
4. Close the browser instead of inputting the verification code
5. Go to http://kaagapai-dev:3000/signup again
6. Enter the same account information
7. Click 'Next'
8. See 'Email is already in use' error (this means you can't proceed to the next step)

**Expected behavior**
1. Go to http://kaagapai-dev:3000/signup
2. Completely fill out the form on the 'Account Registration' step
3. Click 'Next'
4. Close the browser instead of inputting the verification code
5. Go to http://kaagapai-dev:3000/signup again
6. Enter the same account information
7. Click 'Next'
8. Receive new verification code
9. Enter new verification code
10. Click 'Next'
11. Be able to see step 3 of account registration (this means that you are sent an email that will tell you to wait for the administrator's approval)

**Screenshots**
<img width="1278" alt="Screen Shot 2019-04-19 at 9 43 23 PM" src="https://user-images.githubusercontent.com/35596494/56427051-090b0880-62ed-11e9-94ba-3e2d37ceb53e.png">
<img width="1280" alt="Screen Shot 2019-04-19 at 9 43 41 PM" src="https://user-images.githubusercontent.com/35596494/56427063-0f998000-62ed-11e9-9f19-0d7fafad3d95.png">
<img width="1280" alt="Screen Shot 2019-04-19 at 9 46 08 PM" src="https://user-images.githubusercontent.com/35596494/56427068-145e3400-62ed-11e9-88f8-5ede93c955db.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave (Version 10.14.1)
 - Browser: Google Chrome
 - Version: 74

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
Maybe look into Gmail's registration process because I think they have the same process as we do.

**Comment by erikatorio** [comment]
The issue has already been addressed, as seen in this commit: [https://github.com/prometheus-tech/kaagapAI/commit/6655f01d4bd2d78a8daab71111cfe60ca615cd7b](url). If an email already in the database is found but is not yet verified, it would just update that email with a new verification code. The existing registration of a practitioner error would only appear if the email registered is verified already.

**Comment by julianaubrey** [comment]
I have an issue on how you addressed this issue. Imagine if I opened two tabs for the sign up process. The first tab I enter my data and click next. Then the second tab I enter a different set of data (i.e., different first name, last name, password, etc.) but I have the same email with the first tab and click next. On my email account I am now receiving two messages from _kaagapai_. If the first tab enters the more recent verification code and click next, you will notice that the data for that account is the data entered on the second tab (which supposed to be is not the case).

**Comment by julianaubrey** [comment]
Let's close this issue and create a separate one for documentation purposes.
