### ISSUE TITLE
Kindly fix the error message in login management

### ISSUE THREAD

**Issue by RandyPaulEspejo** [prometheus-tech/kaagapAI#8]
**Describe the bug**
- kindly fix the error message when the user invalid to enter his/her correct username and password it is not showing

**To Reproduce**
1. Go to '..enter invalid username and password.'
2. Click on '..login button..'
4. See minor issue

**Expected behavior**
- it must be clearly seen by the user.

**Screenshots**
-
<img width="1436" alt="Screen Shot 2019-04-25 at 11 14 02 AM" src="https://user-images.githubusercontent.com/37105236/56812483-901c2b80-686d-11e9-8346-bf98f580c244.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Mojave
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 73

**Comment by JessieMTabilisma** [comment]
Hi, @RandyPaulEspejo I already resolved the issue by placing the error message after the login message. This message is now visible.
