### ISSUE TITLE
error message on validating the code

### ISSUE THREAD

**Issue by RandyPaulEspejo** [prometheus-tech/kaagapAI#9]
**Describe the bug**
-kindly fix the error message on validating the code 

**To Reproduce**
1. Go to '.register account..'
2. Click on '..continue and show a modal for validating code..'

**Expected behavior**
- error message must be pop up message or a modal.

**Screenshots**
<img width="617" alt="Screen Shot 2019-04-25 at 3 42 31 PM" src="https://user-images.githubusercontent.com/37105236/56718491-71d10580-6771-11e9-8237-700f39242c99.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Mojave
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 73

**Comment by JessieMTabilisma** [comment]
Hi, @RandyPaulEspejo  I already design the error message and turn it to more visible (color). I didn't turn it into a modal or pop up because it was against to the uniform design of the system.

**Comment by RandyPaulEspejo** [comment]
Hi, @JessieMTabilisma thank you!
